### ISSUE TITLE
API to administrate resources in Resouce Registry

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#103]
### Description

Altinn Resource Registry needs to provide API to be able to administrate resources with policies through API

### User stories

- As an org, I should be able to create a resource through API
- As an org, I should be able to update a resource through API
- As an org, I should be able to create a policy for resources through API
- As an org, I should be able to update a policy for resources through API

### Acceptance Criteria

- [x] All required attributes on all required languages need to be set before a resource can be created
- [x] The policy needs to refer to the correct resource when upload
- [x] Only owners of an resource/policy can modify it through API
- [x] Supports Admin usage from Altinn Studio
- [x] Uses maskinporten/exchanged Altinn token
- [x] Requires scopes to allow access

### Development tasks

```[tasklist]
### Design Tasks
```

```[tasklist]
### Development tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/153
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/242
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/20
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/19
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/21
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/26
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/35
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/36
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/43
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/61
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/62
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/65
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/96
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/93
```

```[tasklist]
### Test
```

```[tasklist]
### Bugs & Chores
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/147
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/98
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/96
```

```[tasklist]
### Dependencies
```

**Comment by annerisbakk** [comment]
@mgunnerud Kan denne lukkes?

**Comment by annerisbakk** [comment]
@mgunnerud Ferdig testet?

**Comment by Nyeng** [comment]
Vi lukker denne, den er implementert og rullet ut. Den kan også utføres fra Altinn Studio GUI
