### ISSUE TITLE
Oversikt og mulighet for å liste ut alle ressurser som har en gitt rolle/tilgangsgruppe i sin ressurspolicy

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-resource-registry#109]
Se beskrivelse av behov her: https://github.com/Altinn/altinn-access-management-frontend/issues/133
Denne issuen kan være en duplikat av denne: https://github.com/Altinn/altinn-access-management/issues/92

Man må hente ut rkunne hente ut en liste over ressurser fra A3 som har en definert gjeldende A2 rolle i sin ressurs-policy.

- Det vil være tungt å skulle hente ut informasjon fra alle policyer for alle ressurser og bygge en oversikt hver gang
- Det bør vurderes om man skal lage en egen database (e.l) som har en slik oversikt og en jobb som med jevne mellomrom sjekker om det er gjort endringer i ressurspolicyer. Evt endringer må resultere i en oppdatert oversikt som GUI i profil kan spørre mot
- En slik oversikt vil antagelig også være nyttig for eksterne å spørre mot
- Et slik oversikt vil også f eks kunne anvendes i f eks GETROLES for Tjenesteeier når man skal sjekke om en tjnesteeier har "tjenstlig behov" for å hente ut rolle/tilgangsgruppeinformasjon om bruker for avgiver. Tjenesteier skal (iflge jurist) bare få hente ut informason om rolle/tilgangsgruppe en bruker såfremt rollen/tilgangsgruppen benytter rollen/tilgangsgruppen på deres tjenester (da har de "tjenstlig behov")
- En slik oversikt burde være tilgjengelig for alle uten pålogging via API, da informasjon ikke er sensitiv og svært nyttig i veiledningssammenheng.

**Comment by sivaglen** [comment]
Er denne duplikat av #185

**Comment by sivaglen** [comment]
@ekorra - vi trenger denne for klargjøring av migrering av lenketjenester.

**Comment by TheTechArch** [comment]
Duplicate
