### ISSUE TITLE
Gui and API to import link Service from Altinn 2

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#343]
### Description

We need a gui that allows the service owner to select a link service in Altinn 2 and import it to the resource registry.

### User Stories

- A user should be able to create a resource in resource registry based on metadata from Altinn 2
- The policy from Altinn 2 should be duplicated in to Altinn 3

### Acceptance Criteria

- [ ] Name should be imported from Altinn
- [ ] You should be able to select ID resource registry
- [ ] 

```[tasklist]
### Tasks
```

**Comment by Nyeng** [comment]
Lukkes fordi den nå er i prod, alt annet blir bugs eller teknisk gjeld.
