### ISSUE TITLE
API for lookup of active resource owners in the registry

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-resource-registry#37]
### Description

Multiple user interfaces and views for access management is to have a multiple select filter component to narrow down search results (searching in delegations, services/apps/apis, access groups etc.).

In order to present the list of resource owners which have one or more active services a backend API operation to retrieve this list is needed.

UI example (not final):
![image](https://user-images.githubusercontent.com/40996230/197207579-0db02511-26eb-4f47-81cb-5dbf5db98acf.png)

Clearifications needed:
- Is this open metadata or should it be authorized?
- Filter requirements?
-- Only resource owners of active resources or also possible to get those with inactive resources?
-- Exclusion of "test"-resourceowners?

### Tasks

- [ ] postgresql function
- [ ] ResourceRegistryRepository implementation
- [ ] Controller endpoint

### Acceptance Criterias

- Should be able to get a list of all resource owners from the resource registry
- Should meet the needs of the filter UI component

**Comment by sivaglen** [comment]
@jonkjetiloye - er denne levert i en annen US eller gjenstår det å implementere?

**Comment by jonkjetiloye** [comment]
@sivaglen Vi har løst dette for API-delegering uten å trenge eget backend oppslag av hvem som er ressurseiere i registeret, det at man heller henter dette ut av den totale listen av tilgjengelige delegerbare API.

Men det er vel mulig at dette er noe vi vil trenge senere i ett mer generelt tjenestesøk.

**Comment by sivaglen** [comment]
Denne er løst på en annen måte. Vi har ikke bruk for denne nå. 
Funskjonalitet forbedres i forbindelse med lenketjenester. 
Kan også løses i BFF.
