### ISSUE TITLE
Bug : CreatedBy is shown as the last changed by

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-resource-registry#380]
1. Login to dev.altinn.studio
2. Scroll down to see the list of resources
3. The overview page lists all resources and the createdby, last updated etc. the created by person is listed as the same person for all the resources. It is the last changed person but created by is confusing for the user

![Image](https://github.com/Altinn/altinn-resource-registry/assets/34273718/85d30983-34d0-41d2-a83b-c633fbb19691)

**Comment by mgunnerud** [comment]
Fixed in altinn-studio repo
