### ISSUE TITLE
Feature: Api vendor can register their api resource with Altinn

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-resource-registry#409]
### Description
The api vendor can register their api resource with altinn

### Prerequisite
The service owner has registered their api resource with maskinporten with necessary scopes

### Actors

- Service owner 

### Required Roles in altinn Studio

- Service owner gives the rights to create an api resource in resource register

### Required Roles/ for Api

- Service owner with necessary scope and the organization number

### User Interface
The api resource can be created either via user interface in altinn or altinn api. This section describes the user interface option.
The service owner can login to altinn studio and create an api resource. 
the wireframes for registering a resource in resource register can be found here

### Api
The serviceowner sends create request to resource register api. 

### Validations

- TBD
	
### Api Integration
- NA
### Acceptance Criteria

- Serviceowner is able to register the api resource in Altinn Studio
- 

```[tasklist]
### Implementation Issues
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/103
```

```[tasklist]
### Test
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/439
```

```[tasklist]
### Tasks
```

**Comment by Nyeng** [comment]
Er tatt i bruk, så lukkes.
