### ISSUE TITLE
Define scopes used for resource registry

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-resource-registry#65]
### Description

We need to define the scopes to used for Altinn Resource Registry

### Conclusion

The following scopes will be created

altinn:resourceregistry/resource.read
altinn:resourceregistry/resource.write
altinn:resourceregistry/resource.admin

**Comment by elsand** [comment]
altinn:resourceregistry/resource.read
altinn:resourceregistry/resource.write
altinn:resourceregistry/resource.admin

has been created in VER2 and PROD. Access has been granted to Digdir in both environments.
