### ISSUE TITLE
Design av Frontend for ResourceRegister og registrering av resourcepolicy

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-resource-registry#78]
Det er nå utviklet API for å oppdatere innhold i Ressursregistere (se https://docs.altinn.studio/technology/architecture/components/application/construction/altinn-platform/authorization/resourceregistry/#api). 
Det må utvikles en App slik at tjenesteeier kan oppdatere sine ressurser 
Denne funksjonaliteten skal lages i Altinn studio. 

Brukere av app vil være fagressurser/tjensteutviklere hos tjenesteeiere som bruker Altinn Autrisasjon. 
Tjenesteeier trenger ikke være utvikler av app av Altinn Studio. 

Hvilke egenskaper en ressurs har er beskrevet her: https://docs.altinn.studio/technology/solutions/altinn-platform/authorization/resourceregistry/#resource-attributes

App skal må som et minimum tilby følgende funskjonalitet: 
- Pålogging. Bruker må (på en eller annen måte) få tilgang til å redigere ressurser på vegne av tjeneseeier
- Oversikt over ressurser
- Mulighet for å opprette nye ressurser
- Mulighet for å redigere ressurser
- Mulighet for å definere policy (regler) knyttet til ressurs
- Mulighet for å produksjonssette ressurser til ulike miljø (inkl) 
- Mulighet for å deaktivere ressurser i ulike miljø

**Comment by TheTechArch** [comment]
Close this
